import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import LatestTrivia from "./component/LatestTrivia";
import FeaturedConstituency from "./component/FeatureCon";
import ElectionGraphicsComponent from "./component/GraphicsWidget";
import ElectionHighlights from "./component/LatestHighlight";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Election_Framework</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <FeaturedConstituency />

      <p>--------------------------------------</p>
      {/* <ElectionGraphicsComponent /> */}
      <ElectionHighlights />
    </div>
  );
}
